### ISSUE TITLE
Browsersupport: Cant start Unity FrontEnd

### ISSUE THREAD

**Issue by rikkuporta** [MOMIND/MOMIND#7]
| Chromium47x64 on Ubuntu15.10x64: |
| --- |

Offline:
![image](https://cloud.githubusercontent.com/assets/3002584/12333328/ddc4a928-baf3-11e5-9862-11b2046ac5e0.png)
Online:
![image](https://cloud.githubusercontent.com/assets/3002584/12333870/065fd760-baf7-11e5-953e-0681fe744ae9.png)

| Firefox43 on Ubuntu15.10x64: |
| --- |

Offline:
![image](https://cloud.githubusercontent.com/assets/3002584/12333349/fc6d41c8-baf3-11e5-9b37-77e253cc2515.png)
Online: No errors, everything works

| Google Chrome47x64 on Ubuntu15.10x64 |
| --- |

Offline: Works, but small error
![image](https://cloud.githubusercontent.com/assets/3002584/12333427/726c0ad0-baf4-11e5-934a-13f305b4836a.png)
Online:
![image](https://cloud.githubusercontent.com/assets/3002584/12333938/6e717de0-baf7-11e5-8916-86f03c561b91.png)

**Comment by DrFritzi** [comment]
Layout Rebuilder errors can be ignored. Favicon error should not influence the unity calls.

The problem is in the public/index.html, were the modules point to the release folder, instead of the development. The data in the release folder is already gziped, and can only be served by a webserver with .htaccess ruling.

We should make a devindex.html for development.

**Comment by rikkuporta** [comment]
deprecated
